### ISSUE TITLE
Client hangs if the server dies

### ISSUE THREAD

**Issue by dzervas** [panagiks/reverse_shell#11]
If the server dies the client will just sit there, running, doing nothing.
I think that the client should try to reconnect every x seconds.

**Comment by panagiks** [comment]
Will add to TODO.

**Comment by panagiks** [comment]
Theoretically fixed in last version. Needs extensive testing. Will test myself but you (and anyone interested) can chip in by testing and trying to recreate the problem in the latest version (it'd be one of these times when it's actually good if we all fail :p)
