### ISSUE TITLE
No Notifications

### ISSUE THREAD

**Issue by dzervas** [panagiks/reverse_shell#12]
The server does not tell anything about what's going on.
Did a client connect/disconnect/died/etc.
A log would be useful too (when all these happened)

**Comment by panagiks** [comment]
Printing messages in console would break the program's flow. Logging is a great idea so will add to TODO.

**Comment by dzervas** [comment]
What do you mean break the program's flow?
The output (I was thinking that readline i kinda better for the server) or the whole structured flow (sockets n' stuff)?

**Comment by panagiks** [comment]
Since you can print all the connected hosts there is no need for an intrusive print in the console when any event occurs. Logging them (as you also suggested) on the other hand would be very useful.

**Comment by dzervas** [comment]
As you wish!
I may start implementing it after the client disconnection bug

**Comment by panagiks** [comment]
Closing this, since in the latest version basic logging was implemented. Will open a new issue about expanding and bettering the current logging system.
