### ISSUE TITLE
Client hoggs CPU if the server go down after the initial connection

### ISSUE THREAD

**Issue by dzervas** [panagiks/reverse_shell#13]
I think this ![this](https://cloud.githubusercontent.com/assets/1029195/16128036/b3b2119c-3407-11e6-9ec8-ca90608397fe.jpg) is kinda problematic :stuck_out_tongue:

**Comment by dzervas** [comment]
This happens when the server disconnects.
The client should connect to the server when executed but after the initial connection, if the server disconnect the client hangs and chews the CPU
Also this is NOT memory leak as the problem is the CPU and not the memory (I didn't check the picture I uploaded...)

**Comment by panagiks** [comment]
First on the list to be solved (and by the way thank you for the bug reports :) ).

**Comment by dzervas** [comment]
I'm currently working on it.

**Comment by panagiks** [comment]
Theoretically fixed in last version. Needs extensive testing. Will test myself but you (and anyone interested) can chip in by testing and trying to recreate the problem in the latest version (it'd be one of these times when it's actually good if we all fail :p)

**Comment by panagiks** [comment]
Fixed by #16
