### ISSUE TITLE
Compatibility with Python3.4

### ISSUE THREAD

**Issue by panagiks** [panagiks/reverse_shell#9]
Should add Compatibility with Python3.4

**Comment by panagiks** [comment]
Pushed back. The Plug-in system doesn't seem to like Python3 soooo let's delay the transition a bit (since there's still an abundance of new features to add).

**Comment by dzervas** [comment]
hmmm...
One of these days I'll test it and fix it (I hope...)

**Comment by panagiks** [comment]
Just a note. In the code added for v0.4.0_rc exec is used as keyword to undertake the dynamic code execution in the scope of the dynamically created module (the mechanism that allows zero disk interaction plugin installation). exec as a keyword seems to not be supported in Python 3. There is exec as a function that seems to be working the same way but I'll have to further test if it acts in the same manner. In any case, when/if we refactor for Python 3 this is one thing to keep in mind.

**Comment by panagiks** [comment]
From what I've seen so far, Python2.7 is still the pre-installed version in most systems. Having this in mind coupled with the complexity and time requirement of maintaining two versions I'm closing this issue.
